//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentC.DataAccess.SQL
{
    using RentC.DataAccess.SQL.Validations;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reservation //:  IValidatableObject
    {

        [Required]
        [ValidPlate]
        public string Plate { get; set; }

        [Required]
        [ValidCustomer]
        public int CustomerID { get; set; }

        [Range(0, 1, ErrorMessage = "Status must e 0 or 1")]
        public byte ReservStatsID { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}")]
        [DataType(DataType.Date)]
       // [ValidStartEndDate]
        [ValidStartDate]
        public DateTime StartDate { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}")]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }

        [Required]
        public string Location { get; set; }

        public string CouponCode { get; set; }

        [Key, Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ReservationID { get; set; }

        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }



        //public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        //{
        //    int result = DateTime.Compare(StartDate, EndDate);
        //    if (result < 0)
        //    {
        //        yield return new ValidationResult("Start Date must be before End Date", new[] { "Confirm Date" });
        //    }
        //}

    }


}
