//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentC.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string Plate { get; set; }
        public int CostumerID { get; set; }
        public byte ReservStatsID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Location { get; set; }
        public string CouponCode { get; set; }
        public int ReservationID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
